CREATE TABLE aluno (
  	RA int,
  	nome varchar(80),
  	fone varchar(30),
  	pai varchar(80),
  	mae varchar(80),
  	data_nasc date
  )
  
  --COMANDO PARA INSERIR (CADASTRAR) UM REGISTRO NA TABELA:
 INSERT INTO aluno
 VALUES (102030, 'ANA', '16999450078', 'JOSE', 'MARIA', '2002-10-18')
  
 INSERT INTO aluno
 VALUES (268975, 'PEDRO', '1699678595', 'PAULO', 'RAFAELA', '2000-09-28')
  
 INSERT INTO aluno
 VALUES (596835, 'IVAN', '16999450256', 'AUGUSTO', 'PATRICIA', '2019-04-20')
  
   --COMANDO PARA SELECIONAR TODOS OS REGISTROS DE UMA TABELA:
 SELECT * 	FROM aluno
  
  --COMANDO PARA ACRESCENTAR UMA COLUNA NOVA A TABELAS:
 ALTER TABLE aluno
 ADD email varchar(50);
  
  --COMANDO PARA EXCLUIR UMA COLUNA DA TABELA:
ALTER TABLE aluno
DROP COLUMN pai
  
  --COMANDO PARA ATUALIZAR VALORES DE UMA COLUNA NA TABELA:
  --CUIDADO! ESTE COMANDO PRECISA DE UM FILTRO PARA NAO AFETAR TODAS AS LINHAS DA TABELA!
UPDATE aluno SET email = 'contato@aluno.com.br'ALTER
WHERE RA = 102030
  
  --O COMANDO WHERE PODE ER USADO PARA FILTRAR LINHAS DA TABELA JUNTO COM OUTROS COMANDOS. EX:
SELECT * from aluno
WHERE RA > 150000
  
SELECT * from aluno
WHERE mae <> 'ANA'
  
 --COMANDO PAR EXCLUIR REGISTRO DA TABELA (APAGAR A LINHA):
DELETE aluno
WHERE mae = 'PATRICIA'
 
 --VER O CONTEUDO DA TABELA APOS EXCLUIR TODOS OS REGISTROS:
SELECT * from aluno
 
 --ORDERNAR O RESULTADO DA CONSULTA:
SELECT * from aluno;
ORDER BY data_nasc DESC